from fastapi import APIRouter, Depends

from app.core.auth import require_business_access

router = APIRouter(prefix="/hr", tags=["hr"])


@router.get("/mock-workspace")
async def get_hr_mock_workspace(
    business_id: str,
    _: str = Depends(require_business_access()),
):
    return {
        "dashboard": {
            "stats": [
                {
                    "title": "Total Applicants",
                    "value": "1,248",
                    "change": "+8%",
                    "tint": "bg-blue-50 text-blue-600",
                    "icon": "users",
                },
                {
                    "title": "Pending Review",
                    "value": "84",
                    "change": "+12%",
                    "tint": "bg-amber-50 text-amber-600",
                    "icon": "briefcase",
                },
                {
                    "title": "Active Interviews",
                    "value": "32",
                    "change": "+6%",
                    "tint": "bg-emerald-50 text-emerald-600",
                    "icon": "calendar",
                },
            ],
            "funnel_stages": [
                {"label": "Applicants", "value": 1248, "width": "100%", "tone": "bg-blue-500"},
                {"label": "AI Screened", "value": 480, "width": "72%", "tone": "bg-blue-400"},
                {"label": "Interviewed", "value": 120, "width": "40%", "tone": "bg-sky-400"},
                {"label": "Hired", "value": 16, "width": "12%", "tone": "bg-cyan-300"},
            ],
            "active_job_postings": [
                {
                    "role": "Senior Frontend Developer",
                    "team": "Engineering",
                    "applicants": 142,
                    "linkedin": "Active",
                    "indeed": "Active",
                    "aiStatus": "Screening",
                },
                {
                    "role": "Product Designer",
                    "team": "Design",
                    "applicants": 89,
                    "linkedin": "Active",
                    "indeed": "Paused",
                    "aiStatus": "Waiting Review",
                },
                {
                    "role": "Marketing Manager",
                    "team": "Marketing",
                    "applicants": 215,
                    "linkedin": "Active",
                    "indeed": "Active",
                    "aiStatus": "Scheduling",
                },
            ],
        },
        "job_postings": {
            "stat_cards": [
                {"label": "Total Postings", "value": "18", "iconClassName": "bg-blue-50 text-blue-600"},
                {"label": "Active", "value": "11", "iconClassName": "bg-emerald-50 text-emerald-600"},
                {"label": "Draft", "value": "4", "iconClassName": "bg-amber-50 text-amber-600"},
                {"label": "Closed", "value": "3", "iconClassName": "bg-slate-100 text-slate-500"},
            ],
            "postings": [
                {
                    "id": "job-1",
                    "title": "Senior Product Designer",
                    "employmentType": "Hybrid - Full time",
                    "department": "Design",
                    "location": "Remote",
                    "postedOn": "Jun 1, 2024",
                    "platforms": ["Li", "In"],
                    "applicants": 47,
                    "applicantBarClassName": "bg-blue-500",
                    "status": "Active",
                },
                {
                    "id": "job-2",
                    "title": "Frontend Engineer",
                    "employmentType": "Hybrid - Full time",
                    "department": "Engineering",
                    "location": "Hybrid - NYC",
                    "postedOn": "May 20, 2024",
                    "platforms": ["Li", "In"],
                    "applicants": 31,
                    "applicantBarClassName": "bg-blue-500",
                    "status": "Active",
                },
                {
                    "id": "job-3",
                    "title": "HR Generalist",
                    "employmentType": "On-site - Full time",
                    "department": "Human Resources",
                    "location": "On-site - LA",
                    "postedOn": "May 20, 2024",
                    "platforms": ["Li", "In"],
                    "applicants": 23,
                    "applicantBarClassName": "bg-blue-500",
                    "status": "Active",
                },
                {
                    "id": "job-4",
                    "title": "Customer Support Rep",
                    "employmentType": "Remote - Part time",
                    "department": "Customer Service",
                    "location": "Remote",
                    "postedOn": "Jun 3, 2024",
                    "platforms": ["Li"],
                    "applicants": 58,
                    "applicantBarClassName": "bg-emerald-500",
                    "status": "Active",
                },
                {
                    "id": "job-5",
                    "title": "Marketing Manager",
                    "employmentType": "Hybrid - Full time",
                    "department": "Marketing",
                    "location": "Hybrid - Chicago",
                    "postedOn": "May 15, 2024",
                    "platforms": ["Li", "In"],
                    "applicants": 14,
                    "applicantBarClassName": "bg-blue-500",
                    "status": "Draft",
                },
                {
                    "id": "job-6",
                    "title": "Sales Development Rep",
                    "employmentType": "On-site - Full time",
                    "department": "Sales",
                    "location": "On-site - Austin",
                    "postedOn": "Apr 30, 2024",
                    "platforms": ["Li"],
                    "applicants": 39,
                    "applicantBarClassName": "bg-blue-500",
                    "status": "Active",
                },
                {
                    "id": "job-7",
                    "title": "Executive Assistant",
                    "employmentType": "On-site - Full time",
                    "department": "Executive",
                    "location": "On-site - NYC",
                    "postedOn": "Apr 27, 2024",
                    "platforms": ["Li", "In"],
                    "applicants": 26,
                    "applicantBarClassName": "bg-blue-500",
                    "status": "Draft",
                },
                {
                    "id": "job-8",
                    "title": "Data Analyst",
                    "employmentType": "Remote - Full time",
                    "department": "Engineering",
                    "location": "Remote",
                    "postedOn": "Mar 18, 2024",
                    "platforms": ["In"],
                    "applicants": 0,
                    "applicantBarClassName": "bg-slate-300",
                    "status": "Closed",
                },
            ],
            "talent_candidates": [
                {
                    "id": "candidate-1",
                    "name": "Elena Rodriguez",
                    "role": "Lead Product Designer",
                    "company": "FinTech Corp",
                    "meta": "6 yrs exp  •  Figma  •  Design Systems",
                    "tags": ["Figma", "UX Strategy"],
                    "match": "91% Match",
                    "matchClassName": "bg-emerald-50 text-emerald-700 border-emerald-200",
                },
                {
                    "id": "candidate-2",
                    "name": "Marcus Chen",
                    "role": "Senior UX Designer",
                    "company": "CreativeHub",
                    "meta": "5 yrs exp  •  UX  •  Startup Prototyping",
                    "tags": ["Product", "Strategy"],
                    "match": "92% Match",
                    "matchClassName": "bg-emerald-50 text-emerald-700 border-emerald-200",
                },
                {
                    "id": "candidate-3",
                    "name": "Sarah Jenkins",
                    "role": "Product Designer",
                    "company": "StartupX",
                    "meta": "4 yrs exp  •  Figma  •  UI Design",
                    "tags": ["Research", "UI"],
                    "match": "85% Match",
                    "matchClassName": "bg-amber-50 text-amber-700 border-amber-200",
                },
            ],
            "interview_questions": [
                {
                    "id": "question-1",
                    "category": "AI Suggested",
                    "prompt": "Walk me through your background and what excites you most about the Senior Product Designer role here.",
                    "meta": "2 follow-ups  •  12 sec  •  Warm-up",
                    "enabled": True,
                    "aiSuggested": True,
                },
                {
                    "id": "question-2",
                    "category": "Core Skill",
                    "prompt": "Tell me about a specific design system project you led, the scope, challenges you faced, and how you measured success.",
                    "meta": "1 follow-up  •  18 sec  •  Systems",
                    "enabled": True,
                },
                {
                    "id": "question-3",
                    "category": "Behavioral",
                    "prompt": "Describe a time when engineering constraints pushed back on a design decision you believed was critical for user experience. How did you handle it?",
                    "meta": "3 follow-ups  •  24 sec  •  Tradeoffs",
                    "enabled": True,
                },
                {
                    "id": "question-4",
                    "category": "AI Suggested",
                    "prompt": "How do you approach mentoring junior designers? Give a specific example of coaching you helped drive significant growth.",
                    "meta": "2 follow-ups  •  16 sec  •  Leadership",
                    "enabled": True,
                    "aiSuggested": True,
                },
                {
                    "id": "question-5",
                    "category": "Removed",
                    "prompt": "Walk me through your most recent end-to-end mobile redesign and how you validated the final experience before launch.",
                    "meta": "Archived  •  Too long for first round",
                    "enabled": False,
                    "archived": True,
                },
                {
                    "id": "question-6",
                    "category": "Culture",
                    "prompt": "What does your ideal design team culture look like, and how do you actively contribute to building it?",
                    "meta": "4 follow-ups  •  20 sec  •  Values",
                    "enabled": True,
                },
            ],
        },
        "candidates": {
            "list": [
                {
                    "id": "elena",
                    "name": "Elena Rodriguez",
                    "role": "Lead Product Designer",
                    "company": "FinTech Corp",
                    "location": "SF",
                    "aiScore": 96,
                    "aiLabel": "Exceptional",
                    "aiTone": "text-emerald-600 border-emerald-300",
                    "summary": "Strong match for leadership criteria. Extensive experience in building design systems from scratch. Passion for dee...",
                    "status": "Shortlisted",
                    "statusClassName": "border-emerald-200 bg-emerald-50 text-emerald-700",
                },
                {
                    "id": "marcus",
                    "name": "Marcus Chen",
                    "role": "Senior UX Designer",
                    "company": "CreativeHub",
                    "location": "NY",
                    "aiScore": 91,
                    "aiLabel": "Strong",
                    "aiTone": "text-emerald-600 border-emerald-300",
                    "summary": "Solid background in B2B SaaS platforms. Excellent prototyping skills and user research methodology. Lacks direct lea...",
                    "status": "New",
                    "statusClassName": "border-blue-200 bg-blue-50 text-blue-700",
                },
                {
                    "id": "sarah",
                    "name": "Sarah Jenkins",
                    "role": "Product Designer",
                    "company": "StartupX",
                    "location": "Remote",
                    "aiScore": 85,
                    "aiLabel": "Match",
                    "aiTone": "text-amber-600 border-amber-300",
                    "summary": "Meets basic requirements for UI design and Figma proficiency. However, falls short on the required 5+ years of...",
                    "status": "New",
                    "statusClassName": "border-blue-200 bg-blue-50 text-blue-700",
                },
                {
                    "id": "david",
                    "name": "David Kim",
                    "role": "Frontend Developer",
                    "company": "TechSolutions",
                    "location": "Seattle",
                    "aiScore": 32,
                    "aiLabel": "Low Match",
                    "aiTone": "text-rose-600 border-rose-300",
                    "summary": "Applicant's background is primarily in frontend engineering. No design portfolio included. Fails most product desig...",
                    "status": "Rejected",
                    "statusClassName": "border-slate-200 bg-slate-100 text-slate-600",
                },
            ]
        },
        "interviews": {
            "rows": [
                {
                    "name": "Elena Rodriguez",
                    "role": "Senior Product Designer",
                    "score": 96,
                    "status": "Interview Done",
                    "statusClassName": "border-blue-200 bg-blue-50 text-blue-700",
                    "date": "Oct 24, 2024",
                    "recommendation": "Strong Hire",
                    "recClassName": "border-emerald-200 bg-emerald-50 text-emerald-700",
                },
                {
                    "name": "Marcus Chen",
                    "role": "Frontend Engineer",
                    "score": 91,
                    "status": "Interview Done",
                    "statusClassName": "border-blue-200 bg-blue-50 text-blue-700",
                    "date": "Oct 23, 2024",
                    "recommendation": "Borderline",
                    "recClassName": "border-amber-200 bg-amber-50 text-amber-700",
                },
                {
                    "name": "Priya Sharma",
                    "role": "UX Researcher",
                    "score": 88,
                    "status": "Shortlisted",
                    "statusClassName": "border-violet-200 bg-violet-50 text-violet-700",
                    "date": "Oct 22, 2024",
                    "recommendation": "Strong Hire",
                    "recClassName": "border-emerald-200 bg-emerald-50 text-emerald-700",
                },
                {
                    "name": "James Okonkwo",
                    "role": "Data Analyst",
                    "score": 42,
                    "status": "Drafting",
                    "statusClassName": "border-slate-200 bg-slate-100 text-slate-600",
                    "date": "Oct 21, 2024",
                    "recommendation": "No Hire",
                    "recClassName": "border-rose-200 bg-rose-50 text-rose-700",
                },
                {
                    "name": "Sofia Kimani",
                    "role": "HR Business Partner",
                    "score": 79,
                    "status": "Interview Done",
                    "statusClassName": "border-blue-200 bg-blue-50 text-blue-700",
                    "date": "Oct 20, 2024",
                    "recommendation": "Hire",
                    "recClassName": "border-emerald-200 bg-emerald-50 text-emerald-700",
                },
                {
                    "name": "Daniel Park",
                    "role": "Backend Engineer",
                    "score": 71,
                    "status": "Pending",
                    "statusClassName": "border-slate-200 bg-slate-100 text-slate-600",
                    "date": "Oct 19, 2024",
                    "recommendation": "Borderline",
                    "recClassName": "border-amber-200 bg-amber-50 text-amber-700",
                },
            ]
        },
        "onboarding": {
            "documents": [
                {
                    "name": "Employee Code of Conduct 2024",
                    "category": "Policy",
                    "tags": ["Workplace", "Culture"],
                    "status": "Reviewed",
                    "statusClassName": "border-emerald-200 bg-emerald-50 text-emerald-700",
                    "date": "Jun 15, 2024",
                    "owner": "Sarah M.",
                    "size": "5.2 MB",
                },
                {
                    "name": "New Hire Onboarding Checklist",
                    "category": "Onboarding",
                    "tags": ["Checklist", "Tasks"],
                    "status": "Published",
                    "statusClassName": "border-emerald-200 bg-emerald-50 text-emerald-700",
                    "date": "Jun 3, 2024",
                    "owner": "James J.",
                    "size": "2.4 MB",
                },
                {
                    "name": "Health & Benefits Overview",
                    "category": "Benefits",
                    "tags": ["Benefits", "Guide"],
                    "status": "Reviewed",
                    "statusClassName": "border-emerald-200 bg-emerald-50 text-emerald-700",
                    "date": "May 29, 2024",
                    "owner": "Sarah M.",
                    "size": "1.8 MB",
                },
                {
                    "name": "Workplace Safety Guidelines",
                    "category": "Compliance",
                    "tags": ["Safety", "Mandatory"],
                    "status": "In Review",
                    "statusClassName": "border-amber-200 bg-amber-50 text-amber-700",
                    "date": "May 20, 2024",
                    "owner": "Mike L.",
                    "size": "3.7 MB",
                },
                {
                    "name": "Anti-Harassment Policy",
                    "category": "Policy",
                    "tags": ["Policy", "HR"],
                    "status": "Reviewed",
                    "statusClassName": "border-emerald-200 bg-emerald-50 text-emerald-700",
                    "date": "May 13, 2024",
                    "owner": "Sarah M.",
                    "size": "1.9 MB",
                },
            ],
            "quick_prompts": [
                "What is the vacation policy?",
                "How do I set up my benefits?",
                "Summarize section 5",
            ],
        },
    }
